resources:
  - name: extensionSources
    type: GitRepo
    configuration:
      path: danielmkn/jfrog-pipelines-extensions-sample    # <-- branch testing is used
      gitProvider: danielMiakotkinGitHub                   # <-- account should have and admin access to the repo
  # Connection of Extension resource
  - name: gkeClusterResource
    type: tutorials/gkeClusterResource
    configuration:
      googleCloudProj: "jfrog-partnership-team"
      gkeClusterZone: "us-central1-c"
      gkeClusterName: "jf-prometheus-grafana"
      googleCloudAuth: gcpK8sPartnershipProject

pipelines:
  - name: daniel_gcp_test
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: Create_GKE_Cluster
        type: tutorials/gkeCreateCluster
        configuration:
          integrations:
            - name: gcpK8sPartnershipProject
          notifyOnSuccess: false
          notifyOnFailure: false
          googleCloudProj: "jfrog-partnership-team"
          gkeClusterZone: "us-central1-c"
          newGkeClusterName: "created-by-pipelines-extension"
          newGkeClusterZone: "us-central1-c"
          num-nodes: 6
          enable-autoscaling: "--enable-autoscaling"
          machine-type: "n1-standard-1"
          min-nodes: 1
          max-nodes: 12
          stuff:
            - "This is a string"
            - "This is another string"
          inputResources:
            - name: gkeClusterResource
            - name: extensionSources
          outputResources:
            - name: gkeClusterResource
            - name: extensionSources
