resources:
  - name: extensionSources
    type: GitRepo
    configuration:
      path: danielmkn/jfrog-pipelines-extensions-sample    # <-- branch testing is used
      gitProvider: danielMiakotkinGitHub                   # <-- account should have and admin access to the repo
  # Connection of Extension resource


  - name: gkeClusterResource
    type: tutorials/gkeClusterResource
    configuration:
      projectName: "jfrog-partnership-team"
      zone: "us-central1-c"
      clusterName: "jf-prometheus-grafana"
      googleCloudAuth: gcpK8sPartnershipProject

pipelines:
  - name: daniel_gcp_test
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: Create_GKE_Cluster
        type: tutorials/gkeCreateCluster
        configuration:
          integrations:
            - name: gcpK8sPartnershipProject
          notifyOnSuccess: false
          notifyOnFailure: false
          stuff:
            - "This is a string"
            - "This is another string"
          inputResources:
            - name: gkeClusterResource
            - name: extensionSources
